### ISSUE TITLE
Example of full text search and relations. 

### ISSUE THREAD

**Issue by omar-shahid** [terence410/ts-mongodb-orm#1]
Hi, I am trying to find a MongoDB driver with Typescript  and found this one. I know this is in its early stage, but since it is production ready, I might use this one. Can anyone give me an example of full text search on a collection and relations with different collections with this package?

**Comment by terence410** [comment]
Hello,

text searching in mongodb is pretty powerful and this library have limited support,

Here is an example you can try for (and it works):

@Index({stringValue: "text"})
@Document()
class QueryTest {
    @Field()
    public _id!: ObjectID;

    @Field()
    public stringValue: string = "";
}

        repository = connection.getRepository(QueryTest);
        await repository.syncIndex();

        const document = new QueryTest();
        document.stringValue = "coffee shop apple";
        await repository.insert(document);

        const document1 = await repository.query().text("coffee apple").findOne();
        assert.isDefined(document1);

        const document2 = await repository.query().text("coff").findOne();
        assert.isUndefined(document2);

        const document3 = await repository.query().text("\"coffee shop\"").findOne();
        assert.isDefined(document3);

        const document4 = await repository.query().text("\"coffee apple\"").findOne();
        assert.isUndefined(document4);

**Comment by omar-shahid** [comment]
Thank you for your reply, I have understood. And how to add relations between collections?

**Comment by ReactReduxRouterDOM** [comment]
How about =like this:

```js
.or(["name", "description"], (x) => {
        x.regex("Wooden Bacon");
      })
```


```js
.and(["name", "description"], (x) => {
        x.regex("Wooden Bacon");
 })
```

It would be much convenient to apply the same condition to multiple columns.

**Comment by terence410** [comment]
the text search is mapping to https://docs.mongodb.com/manual/text-search/, it's related to the field, you can define as many fields as you want

relationship is not supported currently

**Comment by omar-shahid** [comment]
Alright, I have seen mongoose populate method uses two queries, as mongodb hasn't relationships built in, it won't be a big problem to use two queries. Thanks for the answers.

**Comment by terence410** [comment]
yes, there isn't any native relationship in mongo, those are just code level things. If I really need relationship, I just use the id as the index from another object.

**Comment by omar-shahid** [comment]
Agreed!
