### ISSUE TITLE
Cache system?

### ISSUE THREAD

**Issue by sawa-ko** [terence410/ts-mongodb-orm#4]
Is there any way to implement a cache system using this ORM?

Examples:
1. Do not send a document update request to the mongodb server if the document data is the same as what is in the cache.
2. Cache time for document queries, for example: the query for books should have a results cache of 5 seconds, this to prevent multiple queries requests to the mongodb server.
3. If a document is edited from another mongodb client the new results are added to the cache seconds after the cache time configured for "x" schema.

I don't know if it is possible to do this at the moment, but such a feature would be great.

**Comment by terence410** [comment]
You request is pretty project specific. But you can easily achieve what you want by using the library and write your own CacheClass.

**Comment by sawa-ko** [comment]
Any examples?

**Comment by alickmail** [comment]
Should be something like this service:
* https://aws.amazon.com/dynamodb/dax/
