### ISSUE TITLE
Why is "objectField" in SchemeValidation type of any?

### ISSUE THREAD

**Issue by Pdzly** [terence410/ts-mongodb-orm#5]
<img width="978" alt="2022-10-16 11_50_18-ts-mongodb-orm_README md at 2 0 · terence410_ts-mongodb-orm – Mozilla Firefox" src="https://user-images.githubusercontent.com/34943569/196028991-28aa934f-ab7b-425f-8cbc-0a4187d31f38.png">

Why is the objectField type of any but in the validation it says it needs to have a name attribute with type of string?

This would be a little bit more clearer if it has a comment on it or make it a type of an interface with a name attribute

**Comment by terence410** [comment]
well noted. for your concern, I will try to add some comments to explain a bit more.

After all, those type is just TypeScript validation, it's not so related to Mongodb at all, You can of course always create your type for better Type safe.
